import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-black`}
        style={{ fontFamily: "SF Pro Display Bold, sans-serif" }}
      >
        {children}
      </body>
    </html>
  );
}
